model:
  name: rf
  hparams:
    n_estimators: 200
    random_state: 0
    max_train_samples: 20000
    n_jobs: -1

transforms:
  zscore:
    enabled: true
    scope: global
  pca:
    enabled: false
